### PR TITLE
Changed oppositeColor calculation to use the YIQ color model

### LINKED ISSUE #1: OppositeColor calculation is sometimes hard to read
Hello,

I was investigating why the some events are hard to read on my screen (turned up the contrast and brightness, to be fair). However, after investigating with some online accessibility checker tools, the calculation for the opposite colors leads to color combinations with a low contrast ratio.

I used this tool to check: https://webaim.org/resources/contrastchecker/

According to your code, an event-color of "#ffb100" will lead to a **white** text color (opposite color). When checking with the contrast checker, it will give you these results if white is the opposite color:

image

When using a black color, the contrast is much higher, and will lead to better readability.

image

I went online for a bit and I stumbled upon this [blog post](https://24ways.org/2010/calculating-color-contrast), which has the following code snippet:

```js
function getContrastYIQ(hexcolor){
	var r = parseInt(hexcolor.substr(0,2),16);
	var g = parseInt(hexcolor.substr(2,2),16);
	var b = parseInt(hexcolor.substr(4,2),16);
	var yiq = ((r*299)+(g*587)+(b*114))/1000;
	return (yiq >= 128) ? 'black' : 'white';
}
```

Using this function in your code leads to more desirable color contrasts

### PR DESCRIPTION
**Pull request by btastic**
Resolves https://github.com/MMRIZE/CX3_Shared/issues/1

### CODE REVIEW

**Review by eouia — APPROVED** [review]
Thank you

**Comment by eouia** [comment]
By the way, to apply this change, CX3/CX3A modules need to be updated/installed again. I wish I update those modules soon.  At that time, normal users can be aware of this update unless they reinstall or update again. 

Thanks. Always welcome PR.

**Comment by btastic** [comment]
If you update the submodule in your projects, they should get automatically updated via `git pull` in the main project afaik.

**Comment by btastic** [comment]
I created the PRs in CalendarExt3 and CalendarExt3Agenda.

With those in place, users should be able to update the submodule via `git pull`

**Pull request merged**
